import random


# TODO: Decompose into functions


def create_code():
    """ This is to randomly create a four digit code that the codebreaker will attempt to break"""
    code = [0,0,0,0]
    for i in range(4):
        value = random.randint(1, 8) # 8 possible digits
        while value in code:
            value = random.randint(1, 8)  # 8 possible digits
        code[i] = value
    #print(code)
    print('4-digit Code has been set. Digits in range 1 to 8. You have 12 turns to break it.')
    return code

def user_input_check(answer):
    """This part of the code checks if the input recieved from the codebreaker
    to see if it matches with the code generated by the code maker"""
    if len(answer) != 4:
        print("Please enter exactly 4 digits.")
        return False
    
    if not answer.isdigit():
        print("Please enter exactly 4 digits.")
        return False
    return True

def results(code, answer):
    correct_digits_and_position = 0
    correct_digits_only = 0
    for i in range(len(answer)):
        if code[i] == int(answer[i]):
            correct_digits_and_position += 1
        elif int(answer[i]) in code:
            correct_digits_only += 1
    return correct_digits_and_position, correct_digits_only

def results_print(correct_digits_and_position, correct_digits_only):
    print('Number of correct digits in correct place:     '+str(correct_digits_and_position))
    print('Number of correct digits not in correct place: '+str(correct_digits_only))


def get_input(): 
    while True: 
        answer = input('Input 4 digit code: ')
        if user_input_check(answer):
            break
    return answer


def run_game():
    try:
        code = create_code()
        turns = 0
        while turns < 12:
            answer = get_input()
            correct =results(code, answer)
            turns += 1
            if correct:
                correct_digits_and_position, correct_digits_only = results(code, answer)
                results_print(correct_digits_and_position, correct_digits_only)
            if correct_digits_and_position == 4:
                correct = True
                print('Congratulations! You are a codebreaker!')
                break
            else:
                print('Turns left: '+str(12 - turns))
        print('The code was: '+str(code))
    except EOFError:
        print("")
if __name__ == "__main__":
    run_game()
